<?php

namespace ContainerEg4TSMs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KaxLOorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KaxLOor' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KaxLOor'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'note' => ['privates', '.errored..service_locator.KaxLOor.App\\Entity\\Notes', NULL, 'Cannot autowire service ".service_locator.KaxLOor": it references class "App\\Entity\\Notes" but no such service exists.'],
            'qrcodeService' => ['privates', 'App\\Services\\QrcodeService', 'getQrcodeServiceService', true],
        ], [
            'note' => 'App\\Entity\\Notes',
            'qrcodeService' => 'App\\Services\\QrcodeService',
        ]);
    }
}
