<?php

namespace ContainerEg4TSMs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotes2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.KaxLOor.App\Entity\Notes' shared service.
     *
     * @return \App\Entity\Notes
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.KaxLOor": it references class "App\\Entity\\Notes" but no such service exists.');
    }
}
